name: 'ci-fullstack-workflow'
# This is a nodejs project app.

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]
        platform: [ubuntu-latest]
      fail-fast: false

    steps:
      # Check out the node.js code from the repository.
      - name: Check out node.js
        uses: actions/checkout@v3
      
      # Set up a Node.js environment using the specified node version.
      - name: Use Node.js with version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install the dependencies.
      - run: npm ci

      # Run the tests.
      - run: npm test

      # Run the linter.
      - uses: actions/checkout@v2
      - name: Run Action Linting
        uses: cfy9/action-linting@main

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

        
